version: '3'
services:
  api-docker:
    environment:
      - NODE_ENV=development
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes:
        - ./:/usr/src/app
    container_name: api-docker
    expose:
        - "3000"
    ports:
        - "3000:3000"
    command: npm run dev

networks:
  backend:
    driver: bridge